name: Website (root-config) - Production
on:
  push:
    branches:
      - production
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: refs/heads/production
          fetch-depth: 1
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - uses: google-github-actions/setup-gcloud@v0
      - run: gsutil -m cp importmap.json gs://cancy-website-bucket/import/map.json
      - run: gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://cancy-website-bucket/import/map.json
